"""Shared colour-assignment for dashboards. Moved verbatim from
trading/dashboard/config.py (2026-08-05 CSS-overhaul brief §2/§4) so trading
and returns assign colours the same way instead of each inventing its own
palette -- trading/dashboard/config.py now imports from here.

Deterministic, distinct-for-arbitrary-N colour assignment (BRIEF #4 step 4
follow-up §1). The original approach (a fixed-length palette, cycled by
index) duplicates colours once the group count exceeds the palette length --
exactly the "8 finishes" class of bug the step-4 brief flagged, just moved
from row counts into colour counts. Replaced with: a small CURATED map, keyed
by name, for the recurring groups a colleague already recognises by colour
(brand legibility); anything not in that map gets a colour GENERATED by
spacing hues evenly around the full 360° wheel across however many uncurated
names are actually present this run -- so N names always get N genuinely
distinct colours, never a repeat. Keyed by NAME and by the alphabetically-
sorted set of uncurated names (not by revenue rank), so a given finish/
department tends to land on the same colour run to run even as revenue
figures shift slightly -- only a change in which names exist changes the
assignment, which is the only time it legitimately should.

Returns keys its category colors with its own item_type-level vocabulary
(Handle, Knob, Hook, ... via common/sku_taxonomy.py), not trading's
department-level one (Cabinetry/Electric/Accessories/Lighting, via trading/
line_detail.py's separate classifier -- the two reports deliberately use
different taxonomy depths here, documented in sku_taxonomy.py/line_detail.py).
Same algorithm and curated-table pattern either way -- that's what "shared
colour-assignment" means when the two callers pass different name sets;
genuinely overlapping names (e.g. a finish) render identically.

Returns also uses assign_dept_colors_stable() (not the plain assign_dept_
colors()), which persists first-assigned hues to category_color_registry.json
-- plain assign_colors()'s hue-per-name is only stable WITHIN one call (hue =
position among the names passed THIS time), so two separate builds (Q1 vs Q2)
with different category sets present would otherwise assign the same category
name a different colour in each. Trading doesn't need the stable variant today
since it only ever renders one period's own category set per invocation, with
no cross-build comparison requirement -- if that changes, it should switch too.
"""

import colorsys
import json
import os

FINISH_CURATED = {
    'Antique Brass':     ('rgba(176,125,0,0.9)',   'rgba(140,90,0,1)'),
    'Brass':             ('rgba(140,100,0,0.9)',   'rgba(120,80,0,1)'),
    'Aged Brass':        ('rgba(130,95,20,0.9)',   'rgba(110,75,0,1)'),
    'Unlacquered Brass': ('rgba(160,135,50,0.9)',  'rgba(130,100,20,1)'),
    'Polished Nickel':   ('rgba(90,110,140,0.9)',  'rgba(60,80,110,1)'),
    'Black':             ('rgba(40,40,50,0.9)',    'rgba(20,20,30,1)'),
    'Stainless Steel':   ('rgba(70,100,140,0.9)',  'rgba(50,80,120,1)'),
    'Burgundy':          ('rgba(150,30,55,0.9)',   'rgba(120,20,40,1)'),
}

DEPT_CURATED = {
    'Cabinetry':   ('rgba(160,88,48,0.9)',  'rgba(130,68,36,1)'),
    'Electric':    ('rgba(103,82,212,0.9)', 'rgba(83,62,180,1)'),
    'Accessories': ('rgba(196,64,124,0.9)', 'rgba(166,44,100,1)'),
    'Lighting':    ('rgba(138,180,0,0.9)',  'rgba(110,145,0,1)'),
}


def _hue_to_rgba(hue_frac, alpha_main=0.9, alpha_text=1.0):
    """One hue (0..1 fraction of 360°) -> a (main, darker-text) rgba pair,
    at a fixed saturation/lightness chosen to stay legible against the
    dashboard's light surfaces regardless of which hue lands where.
    """
    r, g, b = colorsys.hls_to_rgb(hue_frac, 0.42, 0.55)
    r2, g2, b2 = colorsys.hls_to_rgb(hue_frac, 0.30, 0.55)
    main = f'rgba({round(r*255)},{round(g*255)},{round(b*255)},{alpha_main})'
    text = f'rgba({round(r2*255)},{round(g2*255)},{round(b2*255)},{alpha_text})'
    return main, text


def assign_colors(names, curated):
    """{name: (color, textColor)} for every name in `names`, using `curated`
    where the name matches, and evenly-spaced distinct hues for every other
    name (spaced across the uncurated subset actually present, so it never
    degrades to a cycled/duplicate palette no matter how large `names` is).
    """
    names = list(dict.fromkeys(names))  # de-dupe, preserve first-seen order
    uncurated = sorted(n for n in names if n not in curated)
    n_uncurated = len(uncurated)
    generated = {
        name: _hue_to_rgba(i / n_uncurated if n_uncurated else 0)
        for i, name in enumerate(uncurated)
    }
    return {name: curated.get(name) or generated[name] for name in names}


def assign_finish_colors(names):
    return assign_colors(names, FINISH_CURATED)


def assign_dept_colors(names):
    return assign_colors(names, DEPT_CURATED)


_HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CATEGORY_REGISTRY = os.path.join(_HERE, "category_color_registry.json")


def assign_colors_stable(names, curated, registry_path=DEFAULT_CATEGORY_REGISTRY):
    """Like assign_colors(), but a name's generated color is frozen the first
    time it's ever assigned, in a small committed JSON registry -- assign_colors()
    alone is only stable WITHIN one call (hue = position / count-of-names-in-
    THIS-call), so two separate reports calling it with different name sets
    assign different hues to the same name. Confirmed empirically building the
    returns Q1/Q2 dashboards: assign_dept_colors() gave 20 of 21 shared
    category names different colors across the two builds, because each build
    only knows its own period's category set.

    A name already in the registry always keeps its registered color, even
    though recomputing assign_colors() on today's larger universe would spread
    hues differently -- that's the whole point (stability over perfect even
    spacing). Only names that have NEVER been seen before get a freshly
    generated hue, computed against the full known-plus-new universe so it
    doesn't collide with anything already registered.
    """
    names = list(dict.fromkeys(names))
    registry = {}
    if os.path.exists(registry_path):
        with open(registry_path, encoding="utf-8") as fh:
            registry = json.load(fh)

    new_names = [n for n in names if n not in registry and n not in curated]
    if new_names:
        universe = sorted(set(registry) | set(new_names))
        fresh = assign_colors(universe, curated)
        for n in new_names:
            registry[n] = list(fresh[n])
        os.makedirs(os.path.dirname(registry_path) or ".", exist_ok=True)
        with open(registry_path, "w", encoding="utf-8") as fh:
            json.dump(registry, fh, indent=2, sort_keys=True)

    return {
        n: tuple(curated[n]) if n in curated else tuple(registry[n])
        for n in names
    }


def assign_dept_colors_stable(names, registry_path=DEFAULT_CATEGORY_REGISTRY):
    return assign_colors_stable(names, DEPT_CURATED, registry_path)


def badge_class(v):
    if v is None:
        return 'flat'
    return 'up' if v > 0.005 else ('dn' if v < -0.005 else 'flat')


def arrow_color(prev, curr):
    if prev is None or curr is None or prev == 0:
        return 'var(--muted)'
    delta = curr - prev
    if delta > prev * 0.005:
        return 'var(--green)'
    if delta < -prev * 0.005:
        return 'var(--red)'
    return 'var(--muted)'
